doggofindr/urls.py
from django.conf.urls import url
from . import views
from .views import(
    home,
    myPage,
    about,
    signup,
    deleteImg,
)


#For Web URL configuration
app_name = 'doggofindr'
urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^myPage/$', myPage, name='myPage'),
    url(r'^about/$', about, name='about'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^deleteImg/$', deleteImg, name='deleteImg'),
]

webApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('doggofindr.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doggofindr/models.py
from django.db import models
from django.contrib.auth.models import User
#database for image table
class Image(models.Model):
    imgName = models.CharField(max_length=200, null=True, blank=True) #Image name
    breedName = models.CharField(max_length=200, null=True, blank=True)
    imgFile = models.FileField(null=True, blank=True) #image url
    accuracy = models.FloatField(null=True, default=0)
    author = models.ForeignKey(User,null=True)
    def __str__(self):
        return str(self.imgFile)

doggofindr/forms.py
from django import forms
from .models import Image

#Create a empty form for the Image database table
class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = [
            "imgName",
            "imgFile",
        ]

doggofindr/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.template.context_processors import csrf
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User
from .models import Image
from.forms import ImageForm

def home(request):
    imgs = Image.objects.all().order_by('-id')
    user = request.user
    context = {
        "imgList" : imgs,
        "user": user,
    }
    return render(request, 'doggofindr/index.html',context)

def about(request):
    return render(request,'doggofindr/about.html')

@login_required
def myPage(request):
    user = User.objects.get(username=request.user)
    imageList =[]
    imgs = Image.objects.all().order_by('-id')
    for i in imgs:
        if i.author == user:
            imageList.append(i)
    if request.method == 'POST':
        print("request is POST")
        images = request.FILES.getlist("files") #Get the file from HTML
        if len(images) > 0 :
            for count, x in enumerate(images):
                formImg = ImageForm(request.POST or None, request.FILES or None)#create new image using the Django Form
                new_img = formImg.save(commit=False) #Temporarily saving the new image but not in the database
                new_img.imgFile = x #Set the image file as the file uploaded
                new_img.author = request.user
                new_img.breedName = "Unknown"
                new_img.save() #Save the image in the database
                print(new_img.imgFile)
    user = request.user
    context = {
        "imgList" : imageList,
        "user": user,
    }
    return render(request, 'doggofindr/myPage.html',context)

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=raw_password)
            login(request, user)
            return home(request)
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form':form})

def deleteImg(request):
    if request.method == 'GET':
        start = request.GET.get("action",None)
        deleteImgId =request.GET.get("imgId",None)
        selectedImg = Image.objects.get(pk=deleteImgId)
        selectedImg.delete()
        if start != None:
            data = {
            'imageList':getImageList()
            }
        return JsonResponse(data)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def getImageList():
    imageList = []
    images = Image.objects.all()
    for i in images:
        imageList.append({
            'id':i.id,
            'url':i.imgFile.url,
            'breedName':i.breedName,
            'author':i.author,
        })
    return imageList

doggofindr/templates/base.html
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Find your breed</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="/static/css/base.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% block head %}
    {% endblock %}
  </head>
  <body id="bodyBase">
    <div class="navList">
      <div id="navImage">
        <img id="logo" class="fitImage" src="/media/static/logo.png">
      </div>
      <div class="menu">
        <a><i id="menu-icon" class="material-icons">face</i>{{user.username}}</a>
        <button class="menubtn"><i id="menu-icon" class="material-icons">menu</i></button>
        <div class="menu-content">
          <a class="link" href="{% url 'doggofindr:home' %}">Home</a>
          <a class="link" href="{% url 'doggofindr:myPage' %}">My Page</a></br>
          <a class="link" href="{% url 'doggofindr:about' %}">About</a>
          <a  style="float:left;" class="link" href="{% url 'login' %}">Log In</a>
          <a  style="float:left;" class="link" href="{% url 'logout' %}">Log Out</a>
          <a style="float:left;"class="link" href="{% url 'doggofindr:signup' %}">Sign Up</a>
        </div>
      </div>
    </div>

    <div id="content">
      {% block content %}
      {% endblock %}
    </div>

  </body>
</html>

doggofindr/templates/doggofindr/about.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" type="text/css" href="/static/css/index.css"><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/static/js/index.js"></script>
{% endblock %}
{% block content %}
<div id="masterDiv" class="masterDiv" align="center">
  <div id="headDiv" class="masterDiv headDiv">
    <div id="headTitleDiv" class="masterDiv headDiv">
      <h1>Creators</h1>
    </div>
  </div>
  <div id="content1Div" class="masterdiv" align="center">
    <div class="box">
    <div id= "sirajDiv" class="container gridImgLayout">
      <div class="imgDiv">
        <img src='/media/static/siraj.JPG' class="gridImg" alt="Siraj">
      </div>
      <div class="descDiv">
        <h2>Siraj Zaneer</h2>
        <p class="title">szaneer@purdue.edu</p>
      </div>
    </div>
    <div id= "woosungDiv" class="container gridImgLayout">
      <div class="imgDiv">
        <img src='/media/static/woosung.JPG' class="gridImg" alt="Woosung">
      </div>
      <div class="descDiv">
        <h2>Woosung Kim</h2>
        <p class="title">kim898@purdue.edu</p>
      </div>
    </div>
    </div>
  </div>
</div>



{% endblock %}

doggofindr/templates/doggofindr/index.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" type="text/css" href="/static/css/index.css"><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/static/js/index.js"></script>
{% endblock %}
{% block content %}
<div id="masterDiv" class="masterDiv" align="center">
  <div id="headDiv" class="masterDiv headDiv">
    <div id="headTitleDiv" class="masterDiv headDiv">
      <h1>Public</h1>
    </div>
  </div>

  <div id="content1Div" class="masterdiv" align="center">
      {% for img in imgList %}
        {% if img.imgFile %}
        <!-- <div class="responsive">
          <div class="gallery">
            <a target="_blank" href='{{img.imgFile.url}}'>
              <img id={{img.id}} class="mySlides fitImage" src='{{img.imgFile.url}}' width="600" height="400">
            </a>
            <div class="desc">
              Description
            </div>
          </div>
        </div> -->
        <div class="gridImgLayout container">
          <div class="imgDiv">
            <a target="_blank" href='{{img.imgFile.url}}'>
              <img id={{img.id}} class="gridImg" src='{{img.imgFile.url}}'>
            </a>
          </div>
          <div class="descDiv">
            <h3>{{img.breedName}}</h3>
            <p class="title">{{img.author}}</p>
          </div>
        </div>
        {% endif %}
      {% endfor %}
  </div>
</div>

{% endblock %}

doggofindr/templates/doggofindr/myPage.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" type="text/css" href="/static/css/index.css"><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/static/js/index.js"></script>
<script src="/static/js/myPage.js"></script>
{% endblock %}
{% block content %}
<div id="masterDiv" class="masterDiv" align="center">
  <div id="headDiv" class="masterDiv headDiv">
    <div id="headTitleDiv" class="masterDiv headDiv">
      <h1>Hello {{user}} !</h1>
      <form id="imageForm" method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
        <input type="file" name="files" id="files" multiple hidden>
        <label for="files"><span><i class="material-icons">file_upload</i></span>Upload</label>
        <a id="uploadImage" class="iconBtn" type="button"><i class="material-icons">done</i>Done</a>
        <a id="findBreed" class="iconBtn" type="button"><i class="material-icons">search</i>Find out Dog Breed</a>
      </form>
    </div>
  </div>

  <div id="content1Div" class="masterdiv" align="center">
      {% for img in imgList %}
        {% if img.imgFile %}
        <div class="gridImgLayout container">
          <div class="imgDiv">
            <a target="_blank" href='{{img.imgFile.url}}'>
              <img id={{img.id}} class="gridImg" src='{{img.imgFile.url}}'>
            </a>
          </div>
          <div class="descDiv">
            <h3>{{img.breedName}}</h3>
            <p class="title">{{img.author}}</p>
          </div>
          <a id={{img.id}} class="deleteImg" role="submit"><i id="menu-icon" class="material-icons">delete</i></a>
        </div>
        {% endif %}
      {% endfor %}
  </div>

</div>

{% endblock %}